class GAME_SETTING:
    SCREEN_WIDTH = 500
    SCREEN_HEIGHT = 500
    FPS = 60

class PLAYER_SETTING:
    RADIUS_OBJECT = 10
    
    INITIAL_X = GAME_SETTING.SCREEN_WIDTH//2
    INITIAL_Y = GAME_SETTING.SCREEN_HEIGHT - 20
    
    MAX_FORWARD_VELO = 60    
    MAX_ROTATION_VELO = 10
    MIN_ROTATION_VELO = -MAX_ROTATION_VELO
    
    ACCELERATION_FORWARD = 5
    ACCELERATION_ROTATE = 0.05

class COLOR:
    BLACK = (0, 0, 0)
    WHITE = (255, 255, 255)
    RED = (255, 0, 0)
    GREEN = (0, 255, 0)
    CRYAN = (0, 255, 255)
    PINK = (255, 0, 255)


# RELATED TO REINFORCEMENT LEARNING
class ACTIONS:
    FORWARD_ACCELERATION= 0
    BACKWARD_ACCELERATION = 1
    TURN_LEFT_ACCELERATION= 2
    TURN_RIGHT_ACCELERATION= 3
    DO_NOTHING = 4 # DIFFERENT WITH STOP
    STOP = 5

class EQUATION:
    NO_SOLUTION = 0
    ONE_SOLUTION = 1
    TWO_SOLUTION = 2    

ACTION_SPACE = 5
MAX_EPISODE = 10000
INT_INFINITY = 99999

