paramName: "tu dep trai lam nha"

TOPIC_NAME_LANE_DETECTION: "lane_detection_topic"
TOPIC_NAME_AVOIDANCE: "avoidance_topic"
TOPIC_NAME_CAMERA: "/camera/rgb/image_raw"
TOPIC_NAME_LIDAR: "/scan"
TOPIC_NAME_VELOCITY: "/cmd_vel"
TOPIC_NAME_DECISION_MAKING: "decision_making_topic"
TOPIC_NAME_TRAFFIC_LIGHT: "traffic_light_topic"
TOPIC_NAME_TRAFFIC_SIGN: "traffic_sign_topic"

NODE_NAME_INIT: "init_node_name"
NODE_NAME_AVOIDANCE: "avoidance_node_name"
NODE_NAME_TRAFFIC_SIGN: "traffic_sign_node_name"
NODE_NAME_TRAFFIC_LIGHT: "traffic_light_node_name"
NODE_NAME_DECISION_MAKING: "decision_making_node_name"

MODULE_TRAFFIC_LIGTHS:
  RED: "RED"
  GREEN: "GREEN"
  YELLOW: "YELLOW"

MODULE_TRAFFIC_SIGNS:
  AHEAD: "AHEAD"
  FORBID: "FORBID"
  STOP: "STOP"
  LEFT: "LEFT"
  RIGHT: "RIGHT"
  NONE: "NONE"
  LABEL_TO_TEXT: [AHEAD, FORBID, STOP, LEFT, RIGHT, NONE]

#--------------#
#      Tú      #
#--------------#
Sign:
  EXTRA_SAFETY: 20
  MIN_AREA: 100
  MAX_AREA: 50000
  MIN_WIDTH_HEIGHT: 30
  MIN_ACCURACY: 0.2

# Text:
#     FONT_SIZE : 1.5
#     FIRST_LINE_ORG : (10,40)
#     SECOND_LINE_ORG : (10,90)
#     THICKNESS : 3

## for window
Text:
  FONT_SIZE: 0.5
  FIRST_LINE_ORG: (10,25)
  SECOND_LINE_ORG: (10,50)
  THICKNESS: 2

###########################

Setting:
  MODEL_NAME: "model-110.h5"
  MODEL_PATH: "./assets"
